# AWS keys
auth:
  # An access key with permissions to read and write to the Elasticsearch service
  access_key: {{AWS_ACCESS_KEY}}
  # The secret key to match the access key above
  secret_key: {{AWS_SECRET_ACCESS_KEY}}

# Paths to the Elasticsearch clusters to be managed
clusters:
  eu: {{ELASTICSEARCH_V7_HOST_EU}}
  us: {{ELASTICSEARCH_V7_HOST_US}}
  dev: {{ELASTICSEARCH_V7_HOST_DEV}}
  local: http://localhost:9200

# API keys
keys:
  # Key for the FT content API (V1 and V2)
  capi: {{API_KEY}}
  # Key for the ES interface API
  es_interface: {{ES_INTERFACE_API_KEY}}
